
server:  port: 8888
  
spring:#  profiles:#    active: native
  cloud:    config:      server:
        git:
          uri: https://github.com/DanCunha/microservice-repo
          search-paths: fornecedor#       native:#         search-locations: c:/microservice-repo